<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JarvisNet.SearchWeb</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JarvisNet.Plugins.Sdk\JarvisNet.Plugins.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="JarvisNet.SearchWeb.UnitTests" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.80.1" />
  </ItemGroup>

</Project>
