<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JarvisNet.Core\JarvisNet.Core.csproj" />
    <ProjectReference Include="..\JarvisNet.Plugins.Sdk\JarvisNet.Plugins.Sdk.csproj" />
    <ProjectReference Include="..\JarvisNet.Audio\JarvisNet.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.80.1" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.80.1-alpha" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
